//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEotA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LEotA.Resources.CommonResources.ru", typeof(CommonResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О Нас.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать только активные мероприятия.
        /// </summary>
        internal static string ActiveOnly {
            get {
                return ResourceManager.GetString("ActiveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        internal static string CurrentCulture {
            get {
                return ResourceManager.GetString("CurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите электронную почту.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Извините, но мероприятие уже закончено.
        /// </summary>
        internal static string Eventover {
            get {
                return ResourceManager.GetString("Eventover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мероприятия.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2021 © Международная научно-исследовательская лаборатория «Лингвистическая экология Арктики»..
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наши страницы в соцсетях.
        /// </summary>
        internal static string FooterSocial {
            get {
                return ResourceManager.GetString("FooterSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Галерея.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Международная научно-исследовательская лаборатория «Лингвистическая экология Арктики»..
        /// </summary>
        internal static string LabName {
            get {
                return ResourceManager.GetString("LabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учись.
        /// </summary>
        internal static string Learn {
            get {
                return ResourceManager.GetString("Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локализация.
        /// </summary>
        internal static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Материалы.
        /// </summary>
        internal static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наша команда.
        /// </summary>
        internal static string Ourteam {
            get {
                return ResourceManager.GetString("Ourteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль заново.
        /// </summary>
        internal static string PasswordA {
            get {
                return ResourceManager.GetString("PasswordA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проекты.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публикации.
        /// </summary>
        internal static string Publications {
            get {
                return ResourceManager.GetString("Publications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудники.
        /// </summary>
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
